### ISSUE TITLE
website is not responsive

### ISSUE THREAD

**Issue by adisuyash** [adisuyash/gymnasium#1]
### Screenshots
![Screenshot 2023-06-26 141318](https://github.com/adisuyash/gymnasium/assets/116362593/21d9401c-2d95-4be3-b54f-dec8c97fe12c)
![Screenshot 2023-06-26 141332](https://github.com/adisuyash/gymnasium/assets/116362593/db5a0842-2b36-46ed-8f02-4a376beba342)

**Comment by summerkoushal** [comment]
i would like to work on this issue. Can i get assigned ?

**Comment by adisuyash** [comment]
Of-course yes

**Comment by summerkoushal** [comment]
great then, thank you for assigning. I will get you back with your responsive site within a day or so : )

**Comment by adisuyash** [comment]
Yes please get in touch if you feel any problem 😊

**Comment by summerkoushal** [comment]
ya sure, i'll love it.

**Comment by summerkoushal** [comment]
i created a pr, do check it out. 
thank you !

**Comment by summerkoushal** [comment]
@adisuyash if you want any changes to it. Do let me know

**Comment by adisuyash** [comment]
@summerkoushal Thanks for your valuable contribution.

**Comment by summerkoushal** [comment]
glad you liked it
